# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a0394975e52534474751fef2fb1388954d283e6f692a25f8e198c81498675e2a4a0108f2abe68e79d70f8d8a34cb3987883b3af3c12a71944d606b2fa035fae

test:
  secret_key_base: 4c1cf389860411a1632252033df45d91a751ac4f0d385f9dcb9a49ed6816c9010dfa994a9913097a4034e552b9e9c9927e73a8e9c50dc6e43672b386698d16fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
